import React from 'react';

import Head from 'next/head';

import slides from 'data/mainSlider';

import Layout from 'components/Layout';
import HomeBanner from 'components/HomeBanner';

function Home() {
  return (
    <>
      <Head>
        <title>Metanoia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <HomeBanner slides={slides} />
      </Layout>
    </>
  );
}

export default Home;
